### ISSUE TITLE
Variadic Macros on Microsoft C++ compiler does not work like gcc. 

### ISSUE THREAD

**Issue by ozthekoder** [graphitemaster/glsl-parser#9] opened 2017-01-27 17:18 UTC
When used in Visual Studio 2015/2017 I get compiler errors  that say "OPERATOR has no type identifier class" etc.
I tried to come up with  a fix myself but I am not that savy with c++ macros. If I am doing something wrong in visual studio, can you point me to the right direction? thank you!

**Comment by graphitemaster** [comment] 2017-01-27 18:35
Can you get me an error log? I need to see the actual error message and not a abridged description. The compiler usually provides much more technical and useful diagnostics.

**Comment by ozthekoder** [comment] 2017-01-27 19:02
Sorry about that, I am currently at work and on a mac, will update the issue with the actual error log from my windows pc later. For now, all the info I can provide is the exact line of the error:
[lexemes.h:271](https://github.com/graphitemaster/glsl-parser/blob/master/lexemes.h#L271) which is included in multiple places but it specifically crashes at this #include:
[lexer.h:32](https://github.com/graphitemaster/glsl-parser/blob/master/lexer.h#L32)
and the fact that all single variable macros seem to work, it is the OPERATOR with 3 arguments causing the issue. 

* Also, it worked when I compiled in here => [Visual C++ Online Compiler](http://webcompiler.cloudapp.net/), so possibly some visual studio setting I am missing? 

Again thanks for taking the time to reply.
Cheers.

**Comment by graphitemaster** [comment] 2020-11-01 01:05
Closing this problem since I cannot reproduce it.

**Closed as completed by graphitemaster** 2020-11-01 01:05 UTC
